/**
 * Copyright (c) 2016 Jsoft Company
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package com.jsoft.faces;

/**
 * Feature value which generated by {@link Feature}.
 *
 * @author Jason Wong (super132j@yahoo.com)
 * @version $Id$
 * @since 0.1
 */
public interface FtValue {

    /**
     * Returns the position of the top left corner in the scan window.
     * @return The x coordinate
     */
    int posx();

    /**
     * Returns the position of the top left corner in the scan window.
     * @return The y coordinate
     */
    int posy();

    /**
     * The width of this feature value. The width is the feature that generated
     * for this value and it is different in different value for the same
     * feature.
     * @return The feature width
     */
    int width();

    /**
     * The height of this feature value. The width is the feature that generated
     * for this value and it is different in different value for the same
     * feature.
     * @return The feature height
     */
    int height();

    /**
     * The value of this computed feature.
     * @return The value
     */
    long value();

    /**
     * Default implementation of {@link FtValue}.
     *
     * @author Jason Wong (super132j@yahoo.com)
     * @version $Id$
     * @since 0.1
     */
    class Default implements FtValue {

        /**
         * The x coordinate of the top left corner.
         */
        private final transient int left;

        /**
         * The y coordinate of the top left corner.
         */
        private final transient int top;

        /**
         * The width of the feature.
         */
        private final transient int wdth;

        /**
         * The height of the feature.
         */
        private final transient int hght;

        /**
         * The calculated value of the feature.
         */
        private final transient long result;

        /**
         * Ctor.
         * @param posx The x coordinate of the top left corner.
         * @param posy The y coordinate of the top left corner.
         * @param width The width of the feature
         * @param height The height of the feature
         * @param value The calculated value of the feature
         * @checkstyle ParameterNumberCheck (3 lines)
         */
        public Default(final int posx, final int posy,
            final int width, final int height, final long value) {
            this.left = posx;
            this.top = posy;
            this.wdth = width;
            this.hght = height;
            this.result = value;
        }

        @Override
        public int posx() {
            return this.left;
        }

        @Override
        public int posy() {
            return this.top;
        }

        @Override
        public int width() {
            return this.wdth;
        }

        @Override
        public int height() {
            return this.hght;
        }

        @Override
        public long value() {
            return this.result;
        }

    }
}
